<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="correspondence"
    nsURI="http://emtagent/correspondence/1.0"
    nsPrefix="corr">

  <eClassifiers xsi:type="ecore:EEnum" name="IdentificationStrategy">
    <eLiterals name="XMI_ID" value="0"/>
    <eLiterals name="URI_FRAGMENT" value="1"/>
    <eLiterals name="CONTENT_FINGERPRINT" value="2"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="DeletionPolicy">
    <eLiterals name="CASCADE" value="0"/>
    <eLiterals name="ORPHAN" value="1"/>
    <eLiterals name="TOMBSTONE" value="2"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="CorrespondenceModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceModelURI"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetModelURI"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastSyncedAt"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries"
        upperBound="-1" eType="#//CorrespondenceEntry" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="CorrespondenceEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceIdentifier"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceFingerprint"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetIdentifier"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identificationStrategy"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orphaned"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastSyncedAt"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

</ecore:EPackage>
