package dev.bxagent.generated;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import ${sourcePackageName}.*;
import ${targetPackageName}.*;

/**
 * Test skeleton for ${generatedClassName}.
 * Generated by bx-agent.
 *
 * This test is @Disabled by default as it requires manual test data setup.
 * Enable and customize it with your specific test cases.
 */
@Disabled("Manual test data setup required")
public class ${generatedClassName}Test {

    @Test
    void testForwardTransformation() {
        // TODO: Create a sample ${rootSourceType} instance
        ${rootSourceType} source = ${sourceFactory}.eINSTANCE.create${rootSourceType}();

        // TODO: Set up test data
        // Example: source.setName("Test");

        // Perform transformation
        ${rootTargetType} target = ${generatedClassName}.transform(source);

        // TODO: Add assertions
        assertNotNull(target);
        // Example: assertEquals("Test", target.getName());
    }

    @Test
    void testBackwardTransformation() {
        // TODO: Create a sample ${rootTargetType} instance
        ${rootTargetType} target = ${targetFactory}.eINSTANCE.create${rootTargetType}();

        // TODO: Set up test data
        // Example: target.setName("Test");

        // Perform backward transformation
        ${rootSourceType} source = ${generatedClassName}.transformBack(target);

        // TODO: Add assertions
        assertNotNull(source);
        // Example: assertEquals("Test", source.getName());
    }

    @Test
    void testRoundtripTransformation() {
        // TODO: Create a sample ${rootSourceType} instance
        ${rootSourceType} original = ${sourceFactory}.eINSTANCE.create${rootSourceType}();

        // TODO: Set up test data
        // Example: original.setName("Roundtrip Test");

        // Perform roundtrip: forward then backward
        ${rootTargetType} target = ${generatedClassName}.transform(original);
        ${rootSourceType} result = ${generatedClassName}.transformBack(target);

        // TODO: Add assertions to verify roundtrip consistency
        assertNotNull(result);
        // Example: assertEquals(original.getName(), result.getName());
    }

    @Test
    void testNullHandling() {
        // Test forward with null
        ${rootTargetType} target = ${generatedClassName}.transform(null);
        assertNull(target);

        // Test backward with null
        ${rootSourceType} source = ${generatedClassName}.transformBack(null);
        assertNull(source);
    }
}
