package dev.bxagent.generated;

// EMF imports for source and target packages
import ${sourcePackageName}.*;
import ${targetPackageName}.*;
import org.eclipse.emf.ecore.*;
import org.eclipse.emf.ecore.resource.*;
import org.eclipse.emf.ecore.xmi.XMIResource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.common.util.EList;
import java.util.*;
import dev.bxagent.correspondence.CorrespondenceModel;
import dev.bxagent.correspondence.TransformationContext;
import dev.bxagent.correspondence.SyncConflictPolicy;
import dev.bxagent.correspondence.SyncConflict;
import dev.bxagent.correspondence.SyncResult;

/**
 * Bidirectional EMF transformation: ${sourcePackageName} ↔ ${targetPackageName}
 * Generated by bxagent.
 *
 * WARNING: Do not edit manually - will be overwritten on regeneration.
 */
public class ${generatedClassName} {

<#include "parts/_header.ftl">

    // ════════════════════════════════════════════════════════════════════════
    // Public API
    // ════════════════════════════════════════════════════════════════════════
<#include "parts/_api_overloads.ftl">

    // ════════════════════════════════════════════════════════════════════════
    // Core transformation implementations (batch + incremental, fwd + bwd)
    // ════════════════════════════════════════════════════════════════════════
<#include "parts/_batch_forward.ftl">
<#include "parts/_incremental_forward.ftl">
<#include "parts/_batch_backward.ftl">
<#include "parts/_incremental_backward.ftl">

    // ════════════════════════════════════════════════════════════════════════
    // Phase helpers: object creation, cross-references, edge materialization
    // ════════════════════════════════════════════════════════════════════════
<#include "parts/_phase1_helpers.ftl">
<#include "parts/_cross_refs.ftl">
<#include "parts/_edge_mat.ftl">

    // ════════════════════════════════════════════════════════════════════════
    // Feature-specific helpers
    // ════════════════════════════════════════════════════════════════════════
<#include "parts/_role_based.ftl">
<#include "parts/_per_type.ftl">
<#include "parts/_fingerprint_util.ftl">
<#include "parts/_aggregation.ftl">
<#include "parts/_incremental_helpers.ftl">
<#include "parts/_sync.ftl">
<#include "parts/_structural_dedup.ftl">
}
